#!/bin/bash

# levantando el stack de CI-project
# seteando las variables de ambiente
# setenado ACCESS y KEY para rancher-compose
export RANCHER_COMPOSE=~/Documents/CI/rancher-compose/rancher-compose-v0.8.6
export RANCHER_ACCESS_KEY=`cat $RANCHER_COMPOSE/pehuelche-CI-environ-access-key`
export RANCHER_SECRET_KEY=`cat $RANCHER_COMPOSE//pehuelche-CI-environ-secret-key`
# URL de Rancher
export RANCHER_URL=http://pehuelche.diinf.usach.cl:8080/v1/projects/1a7
# levantando el stack
# con recreate para up buscamos recrear el stack para asegurarnos que los cambios se tomen en cuenta
$RANCHER_COMPOSE/rancher-compose --url $RANCHER_URL \
								 --access-key $RANCHER_ACCESS_KEY \
								 --secret-key $RANCHER_SECRET_KEY \
								 --debug \
								 --env-file docker-compose.env \
								 up \
								 	--recreate