# GitLab CE
# Utilizamos la imagen que se encuentra en Docker Hub, no creamos una imagen nueva para el archivo docker-compose
# https://hub.docker.com/r/gitlab/gitlab-ce/
# Para version estable, ver los tags en
# https://hub.docker.com/r/gitlab/gitlab-ce/tags/