#!/bin/bash

# levantando el stack de prueba en localhost
# seteando las variables de ambiente
# setenado ACCESS y KEY para rancher-compose
export RANCHER_ACCESS_KEY=`cat ~/Documents/CI/rancher-compose-v0.12.1/example-localhost-access-key`
export RANCHER_SECRET_KEY=`cat ~/Documents/CI/rancher-compose-v0.12.1/example-localhost-secret-key`
# URL de Rancher
export RANCHER_URL=http://10.0.2.15:8080/v1
# levantando el stack
# con recreate para up buscamos recrear el stack para asegurarnos que los cambios se tomen en cuenta
rancher-compose --url $RANCHER_URL \
				--access-key $RANCHER_ACCESS_KEY \
				--secret-key $RANCHER_SECRET_KEY \
				--debug \
				up \
                --upgrade